// flow-typed signature: 287e89af7583eaa4b3560921b78b2fe1
// flow-typed version: <<STUB>>/react-redux-loading-bar_v^2.8.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux-loading-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux-loading-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux-loading-bar/build/immutable' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/index' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/loading_bar_ducks' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/loading_bar_middleware' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/loading_bar_redux' {
  declare module.exports: any;
}

declare module 'react-redux-loading-bar/build/loading_bar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux-loading-bar/build/immutable.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/immutable'>;
}
declare module 'react-redux-loading-bar/build/index.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/index'>;
}
declare module 'react-redux-loading-bar/build/loading_bar_ducks.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/loading_bar_ducks'>;
}
declare module 'react-redux-loading-bar/build/loading_bar_middleware.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/loading_bar_middleware'>;
}
declare module 'react-redux-loading-bar/build/loading_bar_redux.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/loading_bar_redux'>;
}
declare module 'react-redux-loading-bar/build/loading_bar.js' {
  declare module.exports: $Exports<'react-redux-loading-bar/build/loading_bar'>;
}
