// flow-typed signature: 5b29d7078898fc36f296c3f65088a21c
// flow-typed version: <<STUB>>/redux-batch-enhancer_v^0.1.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-batch-enhancer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-batch-enhancer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-batch-enhancer/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-batch-enhancer/lib/index.js' {
  declare module.exports: $Exports<'redux-batch-enhancer/lib/index'>;
}
